name: rising-world

services:
  server:
    image: devidian/rising-world-docker:2.1.0
    platform: linux/amd64
    restart: unless-stopped
    init: true
    stop_grace_period: 2m
    environment:
      RW_UPDATE_ON_START: "true"
      RW_VALIDATE: "false"
      RW_INSTALL_OZ_TOOLS: "false"
    volumes:
      - rising-world-data:/appdata/rising-world/dedicated-server
    ports:
      - "4254-4259:4254-4259/udp"
      - "4254-4259:4254-4259/tcp"
    logging:
      driver: local
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  rising-world-data:
